#### Colab에서 런타임이 끊기는 걸 방지하기 위한 코드:

(코드 실행 전 우클릭>검사>Console 에 삽입)

function ClickConnect(){  
console.log("Working");   
document.querySelector("colab-toolbar-button#connect").click()   
}  
setInterval(ClickConnect,60000)

In [12]:
import pandas as pd
import numpy as np
telescope_data=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.data',header=None)

In [13]:
from IPython.display import display

In [14]:
telescope_data.columns = ['fLength', 'fWidth','fSize','fConc','fConcl','fAsym','fM3Long','fM3Trans','fAlpha','fDist','class']
display(telescope_data.head())
display(telescope_data.info())
display(telescope_data.describe())
display(telescope_data['class'].value_counts())

,fLength,fWidth,fSize,fConc,fConcl,fAsym,fM3Long,fM3Trans,fAlpha,fDist,class
0,28.7967,16.0021,2.6449,0.3918,0.1982,27.7004,22.0110,-8.2027,40.0920,81.8828,g
1,31.6036,11.7235,2.5185,0.5303,0.3773,26.2722,23.8238,-9.9574,6.3609,205.2610,g
2,162.0520,136.0310,4.0612,0.0374,0.0187,116.7410,-64.8580,-45.2160,76.9600,256.7880,g
3,23.8172,9.5728,2.3385,0.6147,0.3922,27.2107,-6.4633,-7.1513,10.4490,116.7370,g
4,75.1362,30.9205,3.1611,0.3168,0.1832,-5.5277,28.5525,21.8393,4.6480,356.4620,g

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19020 entries, 0 to 19019
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   fLength   19020 non-null  float64
 1   fWidth    19020 non-null  float64
 2   fSize     19020 non-null  float64
 3   fConc     19020 non-null  float64
 4   fConcl    19020 non-null  float64
 5   fAsym     19020 non-null  float64
 6   fM3Long   19020 non-null  float64
 7   fM3Trans  19020 non-null  float64
 8   fAlpha    19020 non-null  float64
 9   fDist     19020 non-null  float64
 10  class     19020 non-null  object
dtypes: float64(10), object(1)
memory usage: 1.6+ MB

None

,fLength,fWidth,fSize,fConc,fConcl,fAsym,fM3Long,fM3Trans,fAlpha,fDist
count,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000
mean,53.250154,22.180966,2.825017,0.380327,0.214657,-4.331745,10.545545,0.249726,27.645707,193.818026
std,42.364855,18.346056,0.472599,0.182813,0.110511,59.206062,51.000118,20.827439,26.103621,74.731787
min,4.283500,0.000000,1.941300,0.013100,0.000300,-457.916100,-331.780000,-205.894700,0.000000,1.282600
25%,24.336000,11.863800,2.477100,0.235800,0.128475,-20.586550,-12.842775,-10.849375,5.547925,142.492250
50%,37.147700,17.139900,2.739600,0.354150,0.196500,4.013050,15.314100,0.666200,17.679500,191.851450
75%,70.122175,24.739475,3.101600,0.503700,0.285225,24.063700,35.837800,10.946425,45.883550,240.563825
max,334.177000,256.382000,5.323300,0.893000,0.675200,575.240700,238.321000,179.851000,90.000000,495.561000

g    12332
h     6688
Name: class, dtype: int64

In [15]:
telescope_shuffle=telescope_data.iloc[np.random.permutation(len(telescope_data))]
tele=telescope_shuffle.reset_index(drop=True)
tele.head()

,fLength,fWidth,fSize,fConc,fConcl,fAsym,fM3Long,fM3Trans,fAlpha,fDist,class
0,160.2650,40.1667,2.9848,0.1916,0.0979,196.9460,-122.6980,-37.5659,39.5540,152.9810,h
1,12.9644,11.2948,2.0952,0.7470,0.3735,14.9999,0.4805,-11.7862,5.0110,75.2872,g
2,35.2593,28.7212,3.3384,0.2092,0.1053,-5.5941,21.9436,11.4688,29.8043,78.0852,g
3,36.2372,17.3551,2.9809,0.2654,0.1353,46.5544,12.1443,-6.1966,6.4440,166.9480,g
4,28.8406,10.3802,2.4040,0.5089,0.2978,3.7736,22.7713,7.1500,34.5180,141.2210,g

In [16]:
tele['class']=tele['class'].map({'g':0,'h':1})

tele.head()

,fLength,fWidth,fSize,fConc,fConcl,fAsym,fM3Long,fM3Trans,fAlpha,fDist,class
0,160.2650,40.1667,2.9848,0.1916,0.0979,196.9460,-122.6980,-37.5659,39.5540,152.9810,1
1,12.9644,11.2948,2.0952,0.7470,0.3735,14.9999,0.4805,-11.7862,5.0110,75.2872,0
2,35.2593,28.7212,3.3384,0.2092,0.1053,-5.5941,21.9436,11.4688,29.8043,78.0852,0
3,36.2372,17.3551,2.9809,0.2654,0.1353,46.5544,12.1443,-6.1966,6.4440,166.9480,0
4,28.8406,10.3802,2.4040,0.5089,0.2978,3.7736,22.7713,7.1500,34.5180,141.2210,0

In [17]:
tele_class = tele['class'].values

In [18]:
pd.isnull(tele).any()

fLength     False
fWidth      False
fSize       False
fConc       False
fConcl      False
fAsym       False
fM3Long     False
fM3Trans    False
fAlpha      False
fDist       False
class       False
dtype: bool

In [19]:
from sklearn.model_selection import train_test_split
training_indices, validation_indices = training_indices, testing_indices = train_test_split(tele.index,
                                                                                            stratify = tele_class,
                                                                                            train_size=0.75, test_size=0.25)

In [20]:
training_indices.size, validation_indices.size

(14265, 4755)

In [21]:
from tpot import TPOTClassifier
from tpot import TPOTRegressor

tpot = TPOTClassifier(generations=5,verbosity=2, config_dict='TPOT light')

tpot.fit(tele.drop('class',axis=1).loc[training_indices].values,
         tele.loc[training_indices,'class'].values)

HBox(children=(FloatProgress(value=0.0, description='Optimization Progress', max=600.0, style=ProgressStyle(de…

Generation 1 - Current best internal CV score: 0.8494917630564318
Generation 2 - Current best internal CV score: 0.8501927795303189
Generation 3 - Current best internal CV score: 0.8518051174202593
Generation 4 - Current best internal CV score: 0.8518051174202593
Generation 5 - Current best internal CV score: 0.8518051174202593

Best pipeline: DecisionTreeClassifier(DecisionTreeClassifier(input_matrix, criterion=entropy, max_depth=9, min_samples_leaf=1, min_samples_split=3), criterion=gini, max_depth=7, min_samples_leaf=5, min_samples_split=19)

TPOTClassifier(config_dict='TPOT light', crossover_rate=0.1, cv=5,
               disable_update_check=False, early_stop=None, generations=5,
               max_eval_time_mins=5, max_time_mins=None, memory=None,
               mutation_rate=0.9, n_jobs=1, offspring_size=None,
               periodic_checkpoint_folder=None, population_size=100,
               random_state=None, scoring=None, subsample=1.0, template=None,
               use_dask=False, verbosity=2, warm_start=False)